sudo: required

language: python

services:
  - docker

before_install:
  - docker --version

script:
  - docker build -t docker-git .
  - docker run docker-git

deploy:
  - provider: script
    script: ./ci-resources/deploy.sh
    on:
      tags: true
