sudo: required

language: ruby

services:
  - docker

before_install:
- docker --version

jobs:
    include:
        - stage: build
          script:
          - docker build -t docker-git .
          - docker run docker-git
          on:
              tags: false
        - stage: release
          before_script:
          - envsubst < tag-template.json > tag-body.json
          script:
          - ./release.sh
          on:
            tags: false