services:
  - docker

before_install:
- docker version

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t docker-git .
      - docker run docker-git
    - stage: release docker image
      branches:
        only:
        - master      
      script:
      - curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/stevencooney/docker-test/trigger/$DOCKER_HUB_TOKEN
